NumLibrosNomLibroB=input('INGRESA EL NUMERO DE LIBROS EN LA REPRISA SIN ESPACIOS COLOCA UNA ","\nY POSTERIOR A ESO EL NOMBRE DEL LIBRO A BUSCAR\n(6,El principito) (8,Los cuentos de Canterbury):\n').split(",")
ListLibros=input('INGRESA LOS NOMBRES DE LOS LIBROS EN LA RESPISA USANDO UNA "," COMO SEPARACION\nPERO NO SEPARE LAS LETRAS PEGADAS A LA ","').split(",")
print(ListLibros)